### ISSUE TITLE
Missing post build action to store artifacts in freestyle job

### ISSUE THREAD

**Issue by okorach** [TrustInSoft/demo-jenkins#2]
In the Jenkinsfile of the pipeline job, there is a step that explains how to store the artifacts of the analysis.
There is no equivalent in the Freestyle job, it would be good to add it

**Comment by jakub-zwolakowski** [comment]
Here :)

![demo-jenkins_freeflow_5_Post-build_Actions (1)](https://user-images.githubusercontent.com/1905935/233992840-7b0829a3-ce97-466c-92f0-fb3ee39d66a6.png)
